### ISSUE TITLE
INVALID_REQUEST_BODY

### ISSUE THREAD

**Issue by pramodhagadur** [GoodTimeio/public-api-docs#13]
Hi,
I am getting Invalid body reqest in Postman when i try to add tags to users. 

**I was using the Body as** 
_[
    {
        "id": "3c83269d-5f37-4607-85af-6cf0c33a284d",
    }
    {
        "id": "1b697008-502f-42bd-836c-ca0813ea4291",
    },
]_

**Error was** 
_{
    "status": "error",
    "code": 400,
    "requestId": "3e1f8107-950f-48cc-a9ba-835acf010ccb",
    "gtErrorCode": 40021,
    "gtErrorName": "INVALID_REQUEST_BODY"
}_
Can someone guide me is this the correct one?

**Comment by pramodhagadur** [comment]
I am using the below url with Put menthod.
https://a.goodtime.io/api/v1/contacts/:id/tags

**Comment by nadapeter** [comment]
Hi @pramodhagadur ,
Looks like there was a typo on our example request body. 
The request body should follow the standard JSON format which means the comma should be between the items of the list and not after the last item.
Try
```
[
  {
    "id": "3c83269d-5f37-4607-85af-6cf0c33a284d"
  },
  {
    "id": "1b697008-502f-42bd-836c-ca0813ea4291"
  }
]
```

**Comment by pramodhagadur** [comment]
hi @nadapeter 
I tried this, but still gave the same error. 
_[
{
   "id": "e2c99fe2-b7d0-405e-abb1-236866a61cfe"
   }
]_
any other info missing in the body?

**Comment by nadapeter** [comment]
@pramodhagadur Can you try adding the header `Content-Type` with value `application/json`?
I'll update the API doc to reflect that.

**Comment by pramodhagadur** [comment]
Hi @nadapeter ,
Thank you for the prompt reply. it worked now. Need to add the header.
